name: Continuous Deployment
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      # Setup
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Node Environment
        uses: actions/setup-node@v2.1.2
      
      # Build
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      
      # Deploy
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          build_dir: public
          commit_message: Auto commit built site
          jekyll: false
        
