name: Continuous Deployment
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      # Setup
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Node Environment
        uses: actions/setup-node@v2.1.2
      
      # Build
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      
      # Deploy
      - name: Deploy to Github Pages
        uses: rdarida/simple-github-pages-deploy-action@v1
        with:
          git-base-folder: public
          commit-message: Auto build static site
        
